export class School {
  name:string;
  id:string="";
  address:string="";
  city:string="";
  state:string="";
  country:string="";
  phone:string="";
  email:string="";
  logo:File;
  backgroundImage:File;
  theme:string="";
  alternatePhone:string="";
  website:string="";
  activeAcademicSession:Date;
  activeTerm:Date;
  passoutClass:string="";
  enableLicense:string="";
  domain:string="";
}
